language: python
python:
    - "2.7"

cache:
    directories:
        - "~/.platformio"

env:
    - PLATFORMIO_PROJECT_DIR=examples/arduino
    - PLATFORMIO_PROJECT_DIR=examples/mbed

install:
    - pip install -U platformio

script:
    - platformio run -d $PLATFORMIO_PROJECT_DIR
